---
- name: "Clean AWS infrastructure"
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
    - infos.yml
  tasks:

    - name: "Gather instances informations"
      amazon.aws.ec2_instance_info:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ project }}-{{ env }}"
          "tag:project": "{{ project }}"
          "tag:env": "{{ env }}"
      register: ec2_instances

    - name: "Terminate instances"
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        instance_ids: "{{ item.instance_id }}"
        state: absent
      with_items: "{{ ec2_instances.instances }}"

    - name: "Delete security group"
      amazon.aws.ec2_security_group:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        name: "{{ project }}-{{ env }}-sg"
        state: absent

    - name: "Delete keypair"
      amazon.aws.ec2_key:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        name: "{{ project }}-{{ env }}-key"
        state: absent
